CREATE TABLE track_events (
  id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  app_name       text NOT NULL,
  track_id       text NOT NULL,
  track_type     text NOT NULL,
  track_time     timestamptz NOT NULL,
  received_at    timestamptz NOT NULL DEFAULT now(),
  track_data     jsonb NOT NULL DEFAULT '{}',
  app_version    text,
  user_id        text,
  uuid           text,
  session_id     text,
  sdk_version    text NOT NULL,
  sdk_env        text,
  page_origin    text,
  page_path      text,
  page_search    text,
  page_protocol  text,
  page_title     text,
  referrer       text,
  user_agent     text,
  device_type    text,
  mobile_brand   text,
  mobile_model   text,
  os             text,
  os_version     text,
  browser        text,
  browser_version text,
  browser_engine text,
  is_bot         boolean,
  is_webview     boolean,
  language       text,
  orientation    text,
  screen_width   int,
  screen_height  int,
  viewport_width int,
  viewport_height int,
  network_type   text,
  network_effective_type text,
  finger_print   text,
  finger_print_canvas text,
  coordinates    text,
  client_ip      inet,
  CONSTRAINT track_events_app_track_uniq UNIQUE (app_name, track_id)
);

CREATE INDEX track_events_app_time_idx ON track_events (app_name, track_time DESC);
CREATE INDEX track_events_app_type_time_idx ON track_events (app_name, track_type, track_time DESC);
