import type { TrackEvent } from '@fanta/shared'

export const makeEvent = (overrides: Partial<TrackEvent> = {}): TrackEvent => ({
  trackId: 'evt-1',
  trackType: 'PageView',
  trackTime: 1_700_000_000_000,
  trackData: { page: 'home' },
  appName: 'demo',
  uuid: 'uuid-1',
  sessionId: 'sess-1',
  sdkVersion: '0.1.0',
  sdkEnv: 'test',
  pageOrigin: 'http://localhost',
  pagePath: '/',
  pageSearch: '',
  pageProtocol: 'http:',
  pageTitle: 'Home',
  referrer: '',
  userAgent: 'vitest',
  deviceType: 'Desktop',
  mobileBrand: '',
  mobileModel: '',
  os: 'Mac OS X',
  osVersion: '14',
  browser: 'Chrome',
  browserVersion: '120',
  browserEngine: 'Blink',
  isBot: false,
  isWebview: false,
  language: 'zh-CN',
  orientation: 'landscape',
  screenWidth: 1920,
  screenHeight: 1080,
  viewportWidth: 1200,
  viewportHeight: 800,
  networkType: 'wifi',
  networkEffectiveType: '4g',
  fingerPrint: 'fp',
  fingerPrintCanvas: 'fpc',
  ...overrides
})
